#!/usr/bin/env bash

bindir=

## Command parsing ################################################################################
cmd="${1}"; shift

## Argument and option parsing ####################################################################
while (( "$#" )); do
  case "${1}" in
    --channel=*) channel=${1/--channel=/''}; shift ;;
    --mood=*) mood=${1/--mood=/''}; shift ;;
    --quality=*) quality=${1/--quality=/''}; shift ;;
    -c*) channel=${2}; shift; shift ;;
    -m*) mood=${2}; shift; shift ;;
    -q*) quality=${2}; shift; shift ;;
    *)
      case "${cmd}" in
        listen) test -n "${1}" && test -z "${channel}" && channel=${1} ;;
      esac
      shift
    ;;
  esac
done

## Default arguments and options ##################################################################
case "${cmd}" in
  listen) test -z "${quality}" && quality=high ;;
esac

## Argument and option prompting ##################################################################
case "${cmd}" in
  listen)
    test -z "${channel}" && \
      read -e -p 'Enter channel (e.g. groovesalad, defcon, poptron): ' channel
  ;;
esac

## Command functions ##############################################################################
function channels() {
  local channels=$(curl -s -H 'Accept: application/json' http://somafm.com/channels.json | \
    jq -r '.channels | sort_by(.listeners | tonumber) | reverse | .[]' | \
    jq -r '.id + " | " + .listeners + " listeners | " + .description')

  case "${channels}" in
    '') return 1 ;;
    *)
      case "${mood}" in
        '') echo "${channels}" ;;
        *) echo "${channels}" | grep "${mood}" ;;
      esac
    ;;
  esac
}

function help() {
  local a=(${0//\// })
  local bin=${a[${#a[@]}-1]}

  echo 'Usage:'
  echo "  ${bin} channels [--mood=<state>]"
  echo "  ${bin} listen <channel> [--quality=<low|high|highest>]"
  echo
  echo 'Core Commands:'
  echo '  channels    List channels'
  echo '  listen      Listen to channel'
}

function listen() {
  local playlist=$(curl -s -H 'Accept: application/json' http://somafm.com/channels.json | \
    jq -r ".channels | map(select(.id == \"${channel}\")) | .[]" | \
    jq -r ".playlists | map(select(.quality == \"${quality}\")) | limit(1;.[]) | .url")

  case "${playlist}" in
    '') return 1 ;;
    *) mpv "${playlist}" 1> /dev/null ;;
  esac
}

function version() {
  echo 'v0.1.0'
}

## Command routing ################################################################################
case "${cmd}" in
  --help|-h) help; exit 0 ;;
  --version|-v) version; exit 0 ;;
  channels|listen) "${cmd}"; exit "$?" ;;
  *) help; exit 1 ;;
esac
