name: "soma-tests"
on:
  pull_request:
  push:
jobs:
  soma-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.2.0

    # use docker to get around the lack for TTY for fzf and mpv
    - run: docker build . -t test

    - run: docker run -t test expect /soma/tests/no_matches_found
    - run: docker run -t test expect /soma/tests/trance
    - run: docker run -t test expect /soma/tests/version
    - run: docker run -t test expect /soma/tests/version_short
